#!/bin/python3

# sort a dict by value in python using default key argument in std::sorted()
# in python 3.7+, dicts are ordered (you can iterate over them)

# 2024.06.04, by @zachleach
from collections import defaultdict

counter = defaultdict(int)
arr = nums
for num in arr:
    counter[num] += 1

# keys sorted in descending order by value (their frequency)
counter = sorted(counter, key=lambda key: counter[key], reverse=1)

result = []
for i in range(k):
    result += [counter[i]]

return result



